all:
	mpicc main.c
	mpirun -n 4 a.out
	
make1:
	mpicc main.c
	mpirun -n 1 a.out
	
make2:
	mpicc main.c
	mpirun -n 2 a.out
make3:
	mpicc main.c
	mpirun -n 3 a.out
make4:
	mpicc main.c
	mpirun -n 4 a.out
